env:
  POSTGRES_DB: rails_test
  POSTGRES_USER: rails
  POSTGRES_PASSWORD: password

name: Rails PR
on: [push] 
#[workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
    env:
      POSTGRES_USER: ${{ env.DB_USER }}
      POSTGRES_PASSWORD: ${{ env.PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      # Add or replace database setup steps here
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create DB
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run Tests
        run: bundler exec rspec spec/*
      - name: Upload coverage results    
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          
      - name: Install Rubocop
        run: gem install rubocop
      - name: Security audit application code
        run: rubocop