env:
  POSTGRES_DB: rails_test
  POSTGRES_USER: rails
  POSTGRES_PASSWORD: password

name: Rails PR
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:      
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DB_HOST: ${{ env.POSTGRES_DB }}
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/cb_api_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - run: |
          gem install bundler
          bundle install --jobs 4
          bin/rails db:setup
          bundle exec rails test 

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          
      - name: Install Rubocop
        run: gem install rubocop
      - name: Security audit application code
        run: rubocop
