env:
  POSTGRES_DB: rails_test
  POSTGRES_USER: rails
  POSTGRES_PASSWORD: password

name: Rails PR
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:      
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - run: |
          gem install bundler
          bundle install --jobs 4
      
      - name: Setup DB
        env:
          PGHOST: postgres
          PGUSER: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
        run: bin/rails db:create db:schema:load
        
      - name: Run tests
        run: bundle exec rspec 

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
          
  #     - name: Install Rubocop
  #       run: gem install rubocop
  #     - name: Security audit application code
  #       run: rubocop